import { ChecklistSeedTask } from '@/types/checklist.types';

// Helper: compact task definition
type S = ChecklistSeedTask;
const t = (
  phase_label: S['phase_label'], days_before: number, category: S['category'],
  title: string, description: string, adat_filter: string, assignee: S['assignee'], is_required: boolean
): S => ({ 
  phase_label, days_before, category, title, description, 
  adat_tags: adat_filter === 'ALL' ? ['ALL'] : adat_filter.split(',') as any, 
  assignee, is_required 
});

export const MASTER_CHECKLIST: ChecklistSeedTask[] = [
  // ═══ H-6 BULAN (180 days) ═══
  t('H-6 Bulan',180,'VENUE','Diskusikan konsep & tema pernikahan','Tentukan apakah ingin adat penuh, modern, outdoor, atau intimate','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENUE','Tentukan total budget + dana cadangan 10-15%','Alokasikan budget untuk setiap kategori vendor','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENUE','Susun daftar tamu estimasi awal','Buat daftar tamu dari kedua belah pihak keluarga','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENUE','Tentukan tanggal pernikahan','Konsultasi kalender Jawa/Hijriah jika perlu','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENUE','Survey & booking gedung / venue utama','Kunjungi minimal 3 venue dan bandingkan harga','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENUE','Konfirmasi fasilitas venue','Cek kapasitas tamu, parkir, mushola, ruang rias, genset','ALL','BERDUA',true),
  t('H-6 Bulan',180,'KATERING','Booking katering','Cek apakah bundle dengan venue atau terpisah','ALL','BERDUA',true),
  t('H-6 Bulan',180,'DOKUMENTASI','Survey & booking fotografer + videografer','Bandingkan portofolio dan paket harga','ALL','BERDUA',true),
  t('H-6 Bulan',180,'DOKUMENTASI','Diskusikan paket dokumentasi','Paket akad, resepsi, prewedding','ALL','BERDUA',true),
  t('H-6 Bulan',180,'BUSANA_RIAS','Mulai hunting gaun pengantin / kebaya adat','Kunjungi butik atau vendor adat','ALL','PENGANTIN_WANITA',true),
  t('H-6 Bulan',180,'BUSANA_RIAS','Booking Make Up Artist (MUA) utama','MUA berkualitas biasanya full 6-12 bulan sebelumnya','ALL','PENGANTIN_WANITA',true),
  t('H-6 Bulan',180,'BUSANA_RIAS','Tentukan konsep busana','Kebaya modern, adat penuh, atau gaun internasional','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENDOR_HIBURAN','Booking MC / pemandu acara','Pilih MC yang berpengalaman di acara pernikahan adat','ALL','BERDUA',true),
  t('H-6 Bulan',180,'VENDOR_HIBURAN','Booking band / DJ / grup musik','Tentukan genre musik untuk resepsi','ALL','BERDUA',true),
  t('H-6 Bulan',180,'DEKOR_FLORIST','Survey vendor dekorasi & florist','Minta portofolio dan mock-up desain','ALL','BERDUA',true),
  t('H-6 Bulan',180,'DEKOR_FLORIST','Tentukan tema dekorasi & palet warna','Koordinasikan dengan konsep busana & venue','ALL','BERDUA',true),
  t('H-6 Bulan',180,'ADAT_PROSESI','Konsultasi prosesi adat dengan sesepuh','Diskusikan rangkaian adat yang akan dijalankan','JAWA,SUNDA','KELUARGA',true),
  t('H-6 Bulan',180,'ADAT_PROSESI','Hubungi penghulu / KUA untuk pendaftaran awal','Tanyakan syarat & jadwal yang tersedia','ALL','BERDUA',true),
  t('H-6 Bulan',180,'ADAT_PROSESI','Booking grup rebana / hadrah untuk akad','Cari grup yang biasa tampil di acara akad nikah','ISLAMI','KELUARGA',false),
  t('H-6 Bulan',180,'ADAT_PROSESI','Tentukan konsep pengajian pra-nikah','Koordinasi dengan ustadz & keluarga','ISLAMI','KELUARGA',false),
  t('H-6 Bulan',180,'ADAT_PROSESI','Tentukan konsep midodareni','Prosesi malam sebelum akad (adat Jawa)','JAWA','KELUARGA',true),
  t('H-6 Bulan',180,'ADAT_PROSESI','Tentukan konsep ngeuyeuk seureuh','Prosesi malam sebelum akad (adat Sunda)','SUNDA','KELUARGA',true),

  // ═══ H-5 BULAN (150 days) ═══
  t('H-5 Bulan',150,'DOKUMEN_KUA','Urus surat pengantar RT/RW','Sesuai domisili calon pengantin','ALL','BERDUA',true),
  t('H-5 Bulan',150,'DOKUMEN_KUA','Siapkan dokumen: KTP, KK, Akta Lahir, Ijazah','Fotokopi masing-masing minimal 3 rangkap','ALL','BERDUA',true),
  t('H-5 Bulan',150,'DOKUMEN_KUA','Isi formulir N1-N7 di KUA','Ambil formulir di KUA kecamatan','ALL','BERDUA',true),
  t('H-5 Bulan',150,'DOKUMEN_KUA','Imunisasi Tetanus Toxoid (TT)','Wajib syarat KUA untuk calon pengantin wanita','ALL','PENGANTIN_WANITA',true),
  t('H-5 Bulan',150,'DOKUMEN_KUA','Siapkan pas foto background biru','Ukuran 4x6 (1), 3x4 (5), 2x3 (5 lembar)','ALL','BERDUA',true),
  t('H-5 Bulan',150,'DOKUMEN_KUA','Daftarkan bimbingan pra-nikah di KUA','Jika diperlukan oleh KUA setempat','ALL','BERDUA',false),
  t('H-5 Bulan',150,'UNDANGAN','Rancang desain undangan cetak & digital','Koordinasikan dengan tema pernikahan','ALL','BERDUA',true),
  t('H-5 Bulan',150,'UNDANGAN','Kirim save-the-date ke tamu','Idealnya 4-6 bulan sebelum hari H','ALL','BERDUA',true),
  t('H-5 Bulan',150,'UNDANGAN','Finalisasi daftar tamu lengkap','Sertakan nomor WA & alamat setiap tamu','ALL','BERDUA',true),
  t('H-5 Bulan',150,'UNDANGAN','Setup wedding website / undangan digital','Buat halaman undangan online dengan RSVP','ALL','BERDUA',false),
  t('H-5 Bulan',150,'SESERAHAN_MAHAR','Diskusikan isi & konsep seserahan','Koordinasikan dengan keluarga kedua belah pihak','JAWA,SUNDA,ISLAMI','KELUARGA',true),
  t('H-5 Bulan',150,'SESERAHAN_MAHAR','Tentukan mahar: bentuk, nilai, desain','Sesuai kesepakatan keluarga','ALL','PENGANTIN_PRIA',true),
  t('H-5 Bulan',150,'SESERAHAN_MAHAR','Booking vendor seserahan / box hantaran','Pesan custom box jika diperlukan','JAWA,SUNDA,ISLAMI','KELUARGA',true),
  t('H-5 Bulan',150,'TRANSPORTASI','Booking mobil pengantin','Mobil klasik, kuda, atau mobil mewah','ALL','BERDUA',true),
  t('H-5 Bulan',150,'TRANSPORTASI','Rencanakan shuttle bus tamu luar kota','Jika ada tamu dari luar kota dalam jumlah besar','ALL','BERDUA',false),
  t('H-5 Bulan',150,'SOUVENIR','Survey & pilih jenis souvenir','Pilih yang sesuai budget dan tema','ALL','BERDUA',true),
  t('H-5 Bulan',150,'SOUVENIR','Order souvenir','Berikan waktu produksi 2-3 bulan untuk custom','ALL','BERDUA',true),

  // ═══ H-4 BULAN (120 days) ═══
  t('H-4 Bulan',120,'BUSANA_RIAS','Trial makeup pertama','Foto & video hasilnya untuk evaluasi','ALL','PENGANTIN_WANITA',true),
  t('H-4 Bulan',120,'BUSANA_RIAS','Fitting busana pengantin pertama','Cek ukuran dan detail jahitan','ALL','PENGANTIN_WANITA',true),
  t('H-4 Bulan',120,'BUSANA_RIAS','Konfirmasi seragam keluarga & bridesmaids','Tentukan warna, model, dan vendor','ALL','BERDUA',true),
  t('H-4 Bulan',120,'BUSANA_RIAS','Mulai perawatan kulit & rambut rutin','Facial, hair mask, perawatan berkala','ALL','PENGANTIN_WANITA',false),
  t('H-4 Bulan',120,'BUSANA_RIAS','Pilih & beli cincin pernikahan','Sisakan 4-6 minggu untuk ukir nama/tanggal','ALL','BERDUA',true),
  t('H-4 Bulan',120,'KATERING','Tasting menu katering','Pilih menu final untuk akad & resepsi','ALL','BERDUA',true),
  t('H-4 Bulan',120,'KATERING','Konfirmasi menu halal & dietary khusus','Pastikan semua kebutuhan diet tamu terpenuhi','ALL','BERDUA',true),
  t('H-4 Bulan',120,'KATERING','Finalisasi sesi makan','Standing party atau duduk penuh','ALL','BERDUA',true),
  t('H-4 Bulan',120,'DEKOR_FLORIST','Meeting detail vendor dekorasi','Layout panggung, pelaminan, meja tamu','ALL','BERDUA',true),
  t('H-4 Bulan',120,'DEKOR_FLORIST','Pilih jenis bunga & warna','Untuk bouquet & dekorasi keseluruhan','ALL','BERDUA',true),
  t('H-4 Bulan',120,'DEKOR_FLORIST','Tentukan backdrop foto & photobooth','Setup photobooth jika diinginkan','ALL','BERDUA',false),
  t('H-4 Bulan',120,'UNDANGAN','Finalisasi desain undangan cetak','Kirim ke percetakan, minta proof sebelum cetak massal','ALL','BERDUA',true),
  t('H-4 Bulan',120,'UNDANGAN','Setup link RSVP unik per tamu','Buat link personal menggunakan Life-Start','ALL','BERDUA',true),
  t('H-4 Bulan',120,'UNDANGAN','Siapkan template pesan WA blast','Template pesan undangan digital via WhatsApp','ALL','BERDUA',true),
  t('H-4 Bulan',120,'RUNDOWN','Susun rundown acara awal','Draft menit per menit: akad + resepsi','ALL','BERDUA',true),
  t('H-4 Bulan',120,'RUNDOWN','Pilih lagu prosesi','Prosesi masuk, first dance, saweran, dll','ALL','BERDUA',false),
  t('H-4 Bulan',120,'RUNDOWN','Diskusikan setlist dengan band/DJ','Kirim daftar lagu yang diinginkan','ALL','BERDUA',true),

  // ═══ H-3 BULAN (90 days) ═══
  t('H-3 Bulan',90,'VENDOR_HIBURAN','Kirim konfirmasi ke SEMUA vendor','Email/WA konfirmasi ke gedung, foto, katering, dekor, MC','ALL','BERDUA',true),
  t('H-3 Bulan',90,'VENDOR_HIBURAN','Review ulang semua kontrak vendor','Cek jadwal pembayaran tersisa','ALL','BERDUA',true),
  t('H-3 Bulan',90,'VENDOR_HIBURAN','Catat status pembayaran semua vendor','Update di budget tracker: paid/unpaid/partial','ALL','BERDUA',true),
  t('H-3 Bulan',90,'VENDOR_HIBURAN','Simpan kontak darurat semua vendor','Buat daftar kontak PIC setiap vendor','ALL','BERDUA',true),
  t('H-3 Bulan',90,'DOKUMEN_KUA','Daftar resmi ke KUA','Minimal 10 hari kerja sebelum akad','ALL','BERDUA',true),
  t('H-3 Bulan',90,'DOKUMEN_KUA','Konfirmasi penghulu & jadwal akad nikah','Pastikan jadwal sudah terkunci','ALL','BERDUA',true),
  t('H-3 Bulan',90,'DOKUMEN_KUA','Siapkan 2 orang saksi','Nama dan fotokopi KTP saksi','ALL','PENGANTIN_PRIA',true),
  t('H-3 Bulan',90,'DOKUMEN_KUA','Pastikan semua dokumen tidak kadaluarsa','Cek masa berlaku KTP dan akta lahir','ALL','BERDUA',true),
  t('H-3 Bulan',90,'BUSANA_RIAS','Trial makeup final','Foto close-up untuk konfirmasi hasil akhir','ALL','PENGANTIN_WANITA',true),
  t('H-3 Bulan',90,'BUSANA_RIAS','Fitting busana kedua','Cek penyesuaian setelah fitting pertama','ALL','PENGANTIN_WANITA',true),
  t('H-3 Bulan',90,'HONEYMOON','Booking hotel honeymoon & transportasi','Pesan tiket dan penginapan','ALL','PENGANTIN_PRIA',false),
  t('H-3 Bulan',90,'HONEYMOON','Cek validitas paspor','Jika honeymoon ke luar negeri','ALL','BERDUA',false),
  t('H-3 Bulan',90,'HONEYMOON','Siapkan info hotel untuk tamu luar kota','Rekomendasi hotel dekat venue','ALL','BERDUA',false),
  t('H-3 Bulan',90,'KEUANGAN','Review budget aktual vs estimasi','Bandingkan pengeluaran nyata dengan rencana awal','ALL','BERDUA',true),
  t('H-3 Bulan',90,'KEUANGAN','Hitung sisa tagihan vendor belum lunas','Buat daftar vendor yang masih harus dibayar','ALL','BERDUA',true),
  t('H-3 Bulan',90,'KEUANGAN','Diskusikan strategi penerimaan amplop','Siapa yang memegang kotak amplop & pencatatan','ALL','BERDUA',true),

  // ═══ H-2 BULAN (60 days) ═══
  t('H-2 Bulan',60,'UNDANGAN','Kirim undangan cetak','8 minggu sebelum adalah batas ideal','ALL','BERDUA',true),
  t('H-2 Bulan',60,'UNDANGAN','Blast undangan digital via WA','Kirim ke semua tamu dengan link RSVP','ALL','BERDUA',true),
  t('H-2 Bulan',60,'UNDANGAN','Pantau & update status RSVP','Cek konfirmasi tamu setiap minggu','ALL','BERDUA',true),
  t('H-2 Bulan',60,'UNDANGAN','Follow up tamu yang belum konfirmasi','Hubungi via WA secara personal','ALL','BERDUA',true),
  t('H-2 Bulan',60,'UNDANGAN','Susun denah tempat duduk tamu','Seating chart berdasarkan kelompok tamu','ALL','BERDUA',true),
  t('H-2 Bulan',60,'UNDANGAN','Cetak name card & escort card','Untuk penanda meja tamu','ALL','BERDUA',true),
  t('H-2 Bulan',60,'RUNDOWN','Finalisasi rundown detail hari H','Menit per menit, versi final','ALL','BERDUA',true),
  t('H-2 Bulan',60,'RUNDOWN','Kirim rundown ke semua vendor & keluarga','Pastikan semua pihak punya salinan','ALL','BERDUA',true),
  t('H-2 Bulan',60,'RUNDOWN','Konfirmasi jam kedatangan & setup vendor','Pastikan tidak ada bentrok jadwal di venue','ALL','BERDUA',true),
  t('H-2 Bulan',60,'BUSANA_RIAS','Fitting busana final','Bawa sepatu & semua aksesoris untuk dicoba','ALL','PENGANTIN_WANITA',true),
  t('H-2 Bulan',60,'BUSANA_RIAS','Konfirmasi seragam keluarga & bridesmaids','Pastikan semua selesai dan pas','ALL','BERDUA',true),
  t('H-2 Bulan',60,'BUSANA_RIAS','Beli aksesoris hari H','Hairpiece, veil, perhiasan','ALL','PENGANTIN_WANITA',true),
  t('H-2 Bulan',60,'BUSANA_RIAS','Fitting final busana pria','Beskap / jas / baju muslim','ALL','PENGANTIN_PRIA',true),
  t('H-2 Bulan',60,'SOUVENIR','Konfirmasi souvenir ready','Pastikan siap diambil / dikirim ke venue','ALL','BERDUA',true),
  t('H-2 Bulan',60,'SOUVENIR','Siapkan hampers keluarga VIP','Parcel khusus untuk orang tua & keluarga inti','ALL','BERDUA',false),

  // ═══ H-1 BULAN (30 days) ═══
  t('H-1 Bulan',30,'VENDOR_HIBURAN','Konfirmasi ulang semua vendor','Hubungi tiap vendor: jam, lokasi, akses masuk','ALL','BERDUA',true),
  t('H-1 Bulan',30,'VENDOR_HIBURAN','Lunasi semua sisa pembayaran vendor','Pastikan tidak ada tagihan tersisa','ALL','BERDUA',true),
  t('H-1 Bulan',30,'VENDOR_HIBURAN','Siapkan amplop tips vendor','Nominal standar per kategori vendor','ALL','BERDUA',false),
  t('H-1 Bulan',30,'VENDOR_HIBURAN','Konfirmasi teknis venue','Kelistrikan, AC, panggung, wifi','ALL','BERDUA',true),
  t('H-1 Bulan',30,'UNDANGAN','Tutup RSVP — hitung final headcount','Angka pasti tamu yang hadir','ALL','BERDUA',true),
  t('H-1 Bulan',30,'UNDANGAN','Kirim angka final ke katering & venue','Deadline biasanya H-14 atau H-7','ALL','BERDUA',true),
  t('H-1 Bulan',30,'UNDANGAN','Finalisasi seating chart','Berdasarkan konfirmasi akhir tamu','ALL','BERDUA',true),
  t('H-1 Bulan',30,'RUNDOWN','Gladi bersih (rehearsal) di venue','MC, keluarga inti, pager ayu','ALL','BERDUA',true),
  t('H-1 Bulan',30,'RUNDOWN','Briefing semua kru & keluarga','Tugas & posisi masing-masing hari H','ALL','BERDUA',true),
  t('H-1 Bulan',30,'RUNDOWN','Distribusi rundown cetak','Bagikan ke semua pemangku acara','ALL','BERDUA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Persiapkan prosesi siraman','1-3 hari sebelum akad','JAWA,SUNDA','KELUARGA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Persiapkan prosesi midodareni','Malam sebelum akad (adat Jawa)','JAWA','KELUARGA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Persiapkan ngeuyeuk seureuh','Malam sebelum akad (adat Sunda)','SUNDA','KELUARGA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Koordinasikan prosesi seserahan','7-1 hari sebelum pernikahan','JAWA,SUNDA,ISLAMI','KELUARGA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Siapkan dekorasi tarub & janur di rumah','Dekorasi tradisional Jawa','JAWA','KELUARGA',false),
  t('H-1 Bulan',30,'ADAT_PROSESI','Siapkan perlengkapan prosesi Sunda','Telur, harupat, bakakak, beras kuning','SUNDA','KELUARGA',true),
  t('H-1 Bulan',30,'ADAT_PROSESI','Jadwalkan pengajian / tahlilan','Jika tradisi keluarga mengadakan','ISLAMI','KELUARGA',false),
  t('H-1 Bulan',30,'BUSANA_RIAS','Pack semua keperluan hari-H','Masukkan dalam 1 tas khusus pengantin','ALL','PENGANTIN_WANITA',true),
  t('H-1 Bulan',30,'BUSANA_RIAS','Siapkan emergency kit','Safety pin, tisu, cermin, touch-up kit, obat','ALL','PENGANTIN_WANITA',true),
  t('H-1 Bulan',30,'BUSANA_RIAS','Siapkan CINCIN & BUKU NIKAH','Simpan di tempat aman, titipkan ke best man','ALL','BERDUA',true),
  t('H-1 Bulan',30,'BUSANA_RIAS','Siapkan amplop tips vendor','Titipkan ke best man / WO','ALL','PENGANTIN_PRIA',true),
  t('H-1 Bulan',30,'KESEHATAN','Izin cuti kerja','Untuk hari H + honeymoon','ALL','BERDUA',true),
  t('H-1 Bulan',30,'KESEHATAN','Tidur cukup, makan bergizi','Hindari stres berlebih menjelang hari H','ALL','BERDUA',true),
  t('H-1 Bulan',30,'KESEHATAN','Quality time bersama pasangan','Waktu santai sebelum hari besar','ALL','BERDUA',false),
];
