import { Religion, DocParty } from '../types/document.types';

export interface DocumentSeedData {
  category: string;
  doc_name: string;
  party: DocParty;
  is_required: boolean;
}

export const DOCUMENT_MASTER_DATA: Record<Religion, DocumentSeedData[]> = {
  ISLAM: [
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Pengantar Nikah dari Kelurahan/Desa (N1)', party: 'BERSAMA', is_required: true },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Keterangan untuk Menikah (N2)', party: 'BERSAMA', is_required: true },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Persetujuan Mempelai (N3)', party: 'BERSAMA', is_required: true },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Keterangan Asal-Usul (N4)', party: 'BERSAMA', is_required: true },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Izin Orang Tua (N5)', party: 'BERSAMA', is_required: false },
    { category: 'ADMINISTRASI KELURAHAN / DESA', doc_name: 'Surat Keterangan Belum Pernah Menikah', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto latar biru 4x6 (5 lembar) + softcopy', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto latar biru 2x3 (5 lembar) + softcopy', party: 'BERSAMA', is_required: true },
    { category: 'KESEHATAN & BIMBINGAN', doc_name: 'Sertifikat Imunisasi TT (Tetanus Toxoid)', party: 'WANITA', is_required: true },
    { category: 'KESEHATAN & BIMBINGAN', doc_name: 'Sertifikat Layak Kawin (hasil pemeriksaan pranikah)', party: 'BERSAMA', is_required: true },
    { category: 'KESEHATAN & BIMBINGAN', doc_name: 'Sertifikat Bimbingan Perkawinan (Bimwin)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Rekomendasi Nikah dari KUA asal', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai dari Pengadilan Agama', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Kematian pasangan terdahulu', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Buku Nikah sebelumnya', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi Kawin dari Pengadilan Agama', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Izin Pengadilan Agama untuk Poligami', party: 'PRIA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Izin Komandan (khusus TNI/POLRI)', party: 'BERSAMA', is_required: false },
    { category: 'PENDAFTARAN KUA', doc_name: 'Formulir Pendaftaran di SIMKAH', party: 'BERSAMA', is_required: true },
    { category: 'PENDAFTARAN KUA', doc_name: 'Bukti bayar PNBP', party: 'BERSAMA', is_required: true },
  ],
  KRISTEN_PROTESTAN: [
    { category: 'DOKUMEN GEREJA', doc_name: 'Surat Baptis (asli atau fotokopi legalisir)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Surat Sidi', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Gereja', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Surat Permohonan Pemberkatan Pernikahan ke Gereja', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Sertifikat / Surat Keterangan Bimbingan Pranikah', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Warta Jemaat', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN GEREJA', doc_name: 'Surat Rekomendasi dari Gereja asal', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN GEREJA', doc_name: 'KK Jemaat / Kartu Anggota Jemaat', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan dari Kelurahan/Desa', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Kelurahan', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto berwarna berdampingan ukuran 4x6 (4 lembar)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Surat Persetujuan / Pernyataan dari Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Nikah Orang Tua (untuk keperluan wali)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Formulir Pelaporan Pencatatan Sipil (F-2.01)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Surat Keterangan telah terjadi Pemberkatan dari Pendeta', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Saksi', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai Sipil', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Kematian pasangan terdahulu', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi dari Pengadilan Negeri', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Izin Komandan (khusus TNI/POLRI)', party: 'BERSAMA', is_required: false },
  ],
  KATOLIK: [
    { category: 'DOKUMEN PAROKI — Prasyarat Awal', doc_name: 'Surat Baptis terbaru (asli, max 6 bulan)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PAROKI — Prasyarat Awal', doc_name: 'Surat Krisma', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PAROKI — Prasyarat Awal', doc_name: 'Formulir Pendaftaran Perkawinan (ditandatangani Ketua Lingkungan)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PAROKI — Prasyarat Awal', doc_name: 'KK Gereja / Kartu Keluarga Paroki', party: 'BERSAMA', is_required: true },
    { category: 'KURSUS PERSIAPAN PERKAWINAN (KPP)', doc_name: 'Mengikuti Kursus Persiapan Perkawinan (KPP)', party: 'BERSAMA', is_required: true },
    { category: 'KURSUS PERSIAPAN PERKAWINAN (KPP)', doc_name: 'Sertifikat KPP dari paroki penyelenggara', party: 'BERSAMA', is_required: true },
    { category: 'PROSES KANONIK', doc_name: 'Mengikuti sesi Penyelidikan Kanonik dengan Romo Paroki', party: 'BERSAMA', is_required: true },
    { category: 'PROSES KANONIK', doc_name: 'Surat Bebas Halangan (Testimonial Libertatis) dari Paroki asal', party: 'BERSAMA', is_required: false },
    { category: 'PROSES KANONIK', doc_name: 'Surat Izin dari Uskup (Dispensasi Disparitas Kultus)', party: 'BERSAMA', is_required: false },
    { category: 'PROSES KANONIK', doc_name: 'Surat Pernyataan Janji dari pihak non-Katolik', party: 'BERSAMA', is_required: false },
    { category: 'PROSES KANONIK', doc_name: 'Pengumuman/Warta Perkawinan di Gereja', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan dari Kelurahan (N1-N4)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Kelurahan', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto berwarna berdampingan ukuran 4x6 (4 lembar)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Surat Baptis dan Surat Sidi (jika beda denominasi)', party: 'BERSAMA', is_required: false },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Formulir Pelaporan Pencatatan Sipil (F-2.01)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Surat Keterangan telah terjadi Perkawinan dari Romo/Pastor', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Saksi', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai Sipil', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi dari Pengadilan Negeri', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Keterangan dari Tribunal Gereja (Anulasi)', party: 'BERSAMA', is_required: false },
  ],
  HINDU: [
    { category: 'DOKUMEN PHDI & KEAGAMAAN', doc_name: 'Surat Keterangan beragama Hindu dari PHDI setempat', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PHDI & KEAGAMAAN', doc_name: 'Surat Keterangan dari Pandita / Pinandita', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PHDI & KEAGAMAAN', doc_name: 'Surat Pernyataan / Kesediaan mengikuti upacara Wiwaha Widhi', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN PHDI & KEAGAMAAN', doc_name: 'Surat Pengantar dari Banjar Adat / Desa Adat (khusus Bali)', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN PHDI & KEAGAMAAN', doc_name: 'Surat Keterangan Sulinggih', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan dari Kelurahan/Desa', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Kelurahan', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto berwarna berdampingan ukuran 4x6 (4 lembar)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Surat Persetujuan Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Formulir Pelaporan Pencatatan Sipil (F-2.01)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Surat Keterangan telah terjadi Perkawinan dari Pandita/PHDI', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Saksi', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai Sipil', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Kematian pasangan terdahulu', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi dari Pengadilan Negeri', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Pindah Agama (menjadi Hindu)', party: 'BERSAMA', is_required: false },
  ],
  BUDDHA: [
    { category: 'DOKUMEN WALUBI / MAJELIS BUDDHA', doc_name: 'Kartu Anggota Umat Buddha / Surat Keterangan dari majelis/vihara', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN WALUBI / MAJELIS BUDDHA', doc_name: 'Surat Permohonan Pemberkatan Pernikahan ke Vihara/Majelis', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN WALUBI / MAJELIS BUDDHA', doc_name: 'Surat Keterangan dari Bhikkhu / Pandita Buddha', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN WALUBI / MAJELIS BUDDHA', doc_name: 'Sertifikat / Surat Keterangan Bimbingan Pranikah', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan dari Kelurahan/Desa', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Kelurahan', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto berwarna berdampingan ukuran 4x6 (4 lembar)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Surat Persetujuan Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Formulir Pelaporan Pencatatan Sipil (F-2.01)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Surat Keterangan telah terjadi Perkawinan dari Bhikkhu/Pandita Buddha', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Saksi', party: 'BERSAMA', is_required: true },
    { category: 'PASCA PEMBERKATAN (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai Sipil', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Kematian pasangan terdahulu', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi dari Pengadilan Negeri', party: 'BERSAMA', is_required: false },
  ],
  KONGHUCU: [
    { category: 'DOKUMEN MAKIN / MATAKIN', doc_name: 'Kartu Liyuan / Bukti Liyuan (Kartu Anggota Jemaat)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN MAKIN / MATAKIN', doc_name: 'Surat Permohonan Upacara Pernikahan ke MAKIN setempat', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN MAKIN / MATAKIN', doc_name: 'Bukti Transfer Biaya Administrasi ke MAKIN', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN MAKIN / MATAKIN', doc_name: 'Surat Pernyataan Ketua MAKIN tentang keaslian data', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN MAKIN / MATAKIN', doc_name: 'Sertifikat / Surat Keterangan Bimbingan Pranikah', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Pengantar RT/RW', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan dari Kelurahan/Desa', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN KELURAHAN', doc_name: 'Surat Keterangan Belum Pernah Menikah dari Kelurahan', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Pria', party: 'PRIA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi KTP Calon Pengantin Wanita', party: 'WANITA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Kartu Keluarga (KK)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Fotokopi Akta Kelahiran', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Pas foto berwarna berdampingan ukuran 4x6 (4 lembar)', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN IDENTITAS', doc_name: 'Surat Persetujuan Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Formulir Pelaporan Pencatatan Sipil (F-2.01)', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Surat Keterangan telah terjadi Perkawinan dari Hadirawan MAKIN', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Saksi', party: 'BERSAMA', is_required: true },
    { category: 'PASCA UPACARA (DISDUKCAPIL)', doc_name: 'Fotokopi KTP kedua Orang Tua', party: 'BERSAMA', is_required: true },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Cerai Sipil', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Akta Kematian pasangan terdahulu', party: 'BERSAMA', is_required: false },
    { category: 'DOKUMEN TAMBAHAN (KONDISIONAL)', doc_name: 'Surat Dispensasi dari Pengadilan Negeri', party: 'BERSAMA', is_required: false },
  ]
};
